### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [kdex/map-game#2]
https://github.com/kdex/map-game/blob/418444458ae3d1e77e3634b3b0a7af185c9dfd87/src/server/js/db.js#L66

that's a bad idea, which leaks connections. If you want to check a connection, see: http://stackoverflow.com/questions/36120435/verify-database-connection-with-pg-promise-when-starting-an-app

Otherwise, do not use `connect` at all ;)

**Comment by kdex** [comment]
Oh, wow, nice to meet you again, @vitaly-t. I really wonder how you've stumbled across this repository. :smile:

Will fix this as soon as I get home, thanks a lot for the hint! :+1:

**Comment by vitaly-t** [comment]
GitHub can show you all the recent check-ins against the library, which I often read t see how people use it ;)
